version: '3.8'
services:
  server:
    container_name: server-1
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env.docker
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  redis:
    container_name: redis-1
    image: redis:7-alpine
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge