version: '3.8'
services:
  client:
    container_name: client-1
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
      - redis
    networks:
      - app-network

  server:
    container_name: server-1
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env.docker
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    container_name: redis-1
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  

networks:
  app-network:
    driver: bridge

